/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let dsh_memory_local_memory_invoke_parameter_0$schema$value
const dsh_memory_local_memory_invoke_parameter_0$schema = () => (dsh_memory_local_memory_invoke_parameter_0$schema$value ??= z.object({
  'action': z.union([z.literal("overview"), z.literal("providers"), z.literal("models"), z.literal("list"), z.literal("read"), z.literal("save"), z.literal("remove"), z.literal("clear"), z.literal("files"), z.literal("file"), z.literal("export"), z.literal("rebuild"), z.literal("job"), z.literal("projectPolicy"), z.literal("sources"), z.literal("removeSource"), z.literal("connections"), z.literal("connection"), z.literal("binding"), z.literal("knowledgeBases"), z.literal("knowSave"), z.literal("knowRemove"), z.literal("knowToggle"), z.literal("preview"), z.literal("publishConfirm"), z.literal("publications"), z.literal("withdrawRecall"), z.literal("syncNow")]),
  'provider': z.union([z.undefined(), z.string()]).optional(),
  'scope': z.union([z.undefined(), z.string()]).optional(),
  'id': z.union([z.undefined(), z.string()]).optional(),
  'title': z.union([z.undefined(), z.string()]).optional(),
  'content': z.union([z.undefined(), z.string()]).optional(),
  'revision': z.union([z.undefined(), z.number()]).optional(),
  'epoch': z.union([z.undefined(), z.number()]).optional(),
  'confirmation': z.union([z.undefined(), z.string()]).optional(),
  'cursor': z.union([z.undefined(), z.number()]).optional(),
  'limit': z.union([z.undefined(), z.number()]).optional(),
  'use': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
  'generate': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'connection': z.union([z.undefined(), z.object({
  'connectionId': z.string(),
  'baseUrl': z.string(),
  'apiProfile': z.union([z.undefined(), z.string()]).optional(),
  'tenantId': z.union([z.undefined(), z.string()]).optional(),
  'readCredentialRef': z.union([z.undefined(), z.string()]).optional(),
  'publishCredentialRef': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
  'binding': z.union([z.undefined(), z.object({
  'projectId': z.string(),
  'connectionId': z.string(),
  'readKbIds': z.array(z.string()),
  'publishKbId': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
  'previewId': z.union([z.undefined(), z.string()]).optional(),
  'publishId': z.union([z.undefined(), z.string()]).optional(),
}))
let dsh_memory_local_memory_invoke_result$schema$value
const dsh_memory_local_memory_invoke_result$schema = () => (dsh_memory_local_memory_invoke_result$schema$value ??= z.object({
  'json': z.string(),
}))

export const TYPERT = {
  package: 'dsh-memory-local',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-memory-local#memory/invoke',
      service: 'memory',
      namespace: 'memory',
      method: 'invoke',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-memory-local/contracts#ManageRequest',
            create: dsh_memory_local_memory_invoke_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-memory-local/contracts#ManageResult',
        create: dsh_memory_local_memory_invoke_result$schema,
      },
      sourceLocation: {"file":"packages/memory/src/remote-service.ts","line":8,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "插件自有严格 Remote；所有管理调用复用已认证 Connection。",
        "summary": "插件自有严格 Remote；所有管理调用复用已认证 Connection。",
        "tags": [],
        "jsDoc": "/** 插件自有严格 Remote；所有管理调用复用已认证 Connection。 */",
        "key": "memory",
        "exportName": "MemoryRemote",
        "members": [
          {
            "kind": "method",
            "name": "invoke",
            "signature": "@Remote async invoke(request: ManageRequest, signal: AbortSignal): Promise<ManageResult>"
          }
        ],
        "types": [
          {
            "name": "BindingInput",
            "declaration": "export interface BindingInput {\n    projectId: string;\n    connectionId: string;\n    readKbIds: string[];\n    publishKbId?: string;\n}"
          },
          {
            "name": "ConnectionInput",
            "declaration": "export interface ConnectionInput {\n    connectionId: string;\n    baseUrl: string;\n    apiProfile?: string;\n    tenantId?: string;\n    readCredentialRef?: string;\n    publishCredentialRef?: string;\n}"
          },
          {
            "name": "ManageRequest",
            "declaration": "export interface ManageRequest {\n    action: 'overview' | 'providers' | 'models' | 'list' | 'read' | 'save' | 'remove' | 'clear' | 'files' | 'file' | 'export' | 'rebuild' | 'job' | 'projectPolicy' | 'sources' | 'removeSource' | 'connections' | 'connection' | 'binding' | 'knowledgeBases' | 'knowSave' | 'knowRemove' | 'knowToggle' | 'preview' | 'publishConfirm' | 'publications' | 'withdrawRecall' | 'syncNow';\n    provider?: string;\n    scope?: string;\n    id?: string;\n    title?: string;\n    content?: string;\n    revision?: number;\n    epoch?: number;\n    confirmation?: string;\n    cursor?: number;\n    limit?: number;\n    use?: boolean;\n    generate?: boolean;\n    sessionId?: string;\n    connection?: ConnectionInput;\n    binding?: BindingInput;\n    previewId?: string;\n    publishId?: string;\n}"
          },
          {
            "name": "ManageResult",
            "declaration": "export interface ManageResult {\n    json: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
