/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ManageRequest, ManageResult } from 'dsh-memory-local/contracts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d656d6f7279 {
    invoke: (request: ManageRequest, signal?: AbortSignal) => Promise<RemoteResult<ManageResult>>
  }
  interface TypertRemoteMap {
    'memory/invoke': (request: ManageRequest, signal?: AbortSignal) => Promise<RemoteResult<ManageResult>>
  }
  interface TypertRemoteNamespaceMap {
    'memory': TypertRemoteNamespace$6d656d6f7279
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
