import { chromium } from '@playwright/test'
import { writeFile } from 'node:fs/promises'
const browser=await chromium.launch({headless:true})
const page=await browser.newPage({viewport:{width:1600,height:1050}})
page.on('console',msg=>{if(msg.type()==='error')console.log('browser-error',msg.text().replace(/token=[^\s&]+/g,'token=[REDACTED]'))})
page.on('pageerror',error=>console.log('page-error',error.message))
await page.goto(process.env.MEMORY_TEST_URL)
await page.waitForTimeout(2000)
const continueButton=page.getByRole('button',{name:'继续',exact:true})
if(await continueButton.count())await continueButton.click()
await page.waitForTimeout(1000)
console.log('after-continue',(await page.locator('body').innerText()).slice(-2500))
const later=page.getByRole('button',{name:/稍后|跳过/})
if(await later.count())await later.first().click()
await page.waitForTimeout(500)
await page.getByRole('button',{name:'设置',exact:true}).click()
await page.getByText('记忆',{exact:true}).first().click()
await page.waitForTimeout(1000)
await page.screenshot({path:'evidence/p0-web.png',fullPage:true})
await writeFile('evidence/p0-dom.txt',await page.locator('body').innerText())
console.log((await page.locator('body').innerText()).slice(0,3000))
const response=await page.request.post('http://127.0.0.1:18437/api/memory/invoke',{data:{type:'client-request',rpcId:'memory-p0',method:'memory/invoke',payload:{args:{request:{action:'overview'}}}},headers:{Origin:'http://127.0.0.1:18437'}})
console.log('Remote',response.status(),(await response.text()).slice(0,2500))
await browser.close()
